version: '3.6'

services:
   prometheus:
       image: prom/prometheus
       ports:
        - 9090:9090
       volumes:
         - ./metrics/prom-config.yml:/etc/metrics/prom-config.yml
       command:
         - '--config.file=/etc/metrics/prom-config.yml'
       
   grafana:
      image: grafana/grafana
      ports:
      - 3000:3000
