apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheusgrafana
  labels:
    app: task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: prometheus
          image: prometheus:latest
          args:
          - '--config.file=/metrics/prom-config.yml'
          ports:
            - containerPort: 9090
        - name: grafana
          image: grafana/grafana:latest
          
          ports:
            - containerPort: 3000
